version: "3.8"

services:
  postgres:
    build:
      context: ../
      dockerfile: ./docker/postgres/Dockerfile
    image: pyzza_postgres:1.0
    container_name: pyzza_postgres
    ports:
      - 5432
    networks:
      - backend 
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    image: pyzza_backend:1.0
    container_name: pyzza_backend
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - POSTGRES_NAME=pyzza
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 80:8000
    networks:
      - backend
    depends_on:
      - postgres
    volumes:
      - app_data:/var/www

networks:
#  frontend:
#    driver: bridge
  backend:
    driver: bridge

volumes:
  app_data:
  db_data:
